Output summary

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -183,7 +183,9 @@ runs:
       run: |
         mkdir -p metadata
         STEP_SUMMARY_FILE="$GITHUB_WORKSPACE/metadata/step-summary-${{ steps.vars.outputs.component_slug }}.md"
-  
+        
+        set +e 
+        
         tfcmt \
           --config "${{ github.action_path }}/config/atmos_github_summary.yaml" \
           -owner "${{ github.repository_owner }}" \
@@ -207,24 +209,26 @@ runs:
   
         TERRAFORM_RESULT=$?
 
-        #if [[ "${TERRAFORM_RESULT}" == "0" ]]; then
-        #  echo "HAS_CHANGES=false" >> $GITHUB_ENV
-        #else
-        #  echo "HAS_CHANGES=false" >> $GITHUB_ENV
-        #  echo "HAS_ERROR=true" >> $GITHUB_ENV
-        #  echo "TERRAFORM_OUTPUT=$(echo "${TERRAFORM_OUTPUT}" | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" | jq -Rs . )" >> $GITHUB_ENV
-        #  exit ${TERRAFORM_RESULT}
-        #fi
+        set -e
 
-
-        if echo "$TERRAFORM_OUTPUT" | grep -q '^No changes. Your infrastructure matches the configuration.'; then
-          echo "HAS_CHANGES=false" >> $GITHUB_ENV
-          echo "No changes found"
-          rm -f ${STEP_SUMMARY_FILE}
+        
+        if [[ "${TERRAFORM_RESULT}" == "0" ]]; then
+          echo "HAS_ERROR=false" >> $GITHUB_ENV
+        
+          if echo "$TERRAFORM_OUTPUT" | grep -q '^No changes. Your infrastructure matches the configuration.'; then
+            echo "HAS_CHANGES=false" >> $GITHUB_ENV
+            echo "No changes found"
+            rm -f ${STEP_SUMMARY_FILE}
+          else
+            echo "HAS_CHANGES=true" >> $GITHUB_ENV
+            echo "Found changes"
+          fi
         else
-          echo "HAS_CHANGES=true" >> $GITHUB_ENV
-          echo "Found changes"
+          echo "HAS_CHANGES=false" >> $GITHUB_ENV
+          echo "HAS_ERROR=true" >> $GITHUB_ENV
+          exit ${TERRAFORM_RESULT}
         fi
+        
 
     - name: Convert PLANFILE to JSON
       if: env.HAS_CHANGES == 'true'
